import React, { useEffect, useState } from 'react';
import { ResumePreview, TemplateType } from './ResumePreview';
import { LogoIcon } from './icons/LogoIcon';

export const SharedResumeView: React.FC = () => {
    const [data, setData] = useState<any>(null);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        try {
            const params = new URLSearchParams(window.location.search);
            const encoded = params.get('shareData');
            if (!encoded) {
                setError("No resume data found.");
                return;
            }
            
            // Decode: Base64 -> URI Component -> JSON
            const jsonStr = decodeURIComponent(atob(encoded));
            const parsed = JSON.parse(jsonStr);
            setData(parsed);
        } catch (e) {
            console.error("Failed to decode resume:", e);
            setError("Invalid or expired resume link.");
        }
    }, []);

    if (error) {
        return (
            <div className="min-h-screen bg-slate-50 flex flex-col items-center justify-center p-4">
                <div className="bg-white p-8 rounded-2xl shadow-xl text-center max-w-md w-full">
                    <div className="w-16 h-16 bg-red-100 text-red-500 rounded-full flex items-center justify-center mx-auto mb-4">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-8 h-8">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m9-.75a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9 3.75h.008v.008H12v-.008Z" />
                        </svg>
                    </div>
                    <h2 className="text-xl font-bold text-slate-900 mb-2">Oops! Link Error</h2>
                    <p className="text-slate-600 mb-6">{error}</p>
                    <a href="/" className="inline-block px-6 py-2.5 bg-blue-600 text-white rounded-lg font-bold hover:bg-blue-700 transition-colors">
                        Go to JobHero AI
                    </a>
                </div>
            </div>
        );
    }

    if (!data) {
        return (
            <div className="min-h-screen bg-slate-50 flex items-center justify-center">
                <div className="animate-pulse flex flex-col items-center">
                    <div className="w-12 h-12 border-4 border-blue-600 border-t-transparent rounded-full animate-spin mb-4"></div>
                    <p className="text-slate-500 font-medium">Loading Resume...</p>
                </div>
            </div>
        );
    }

    const mockUserInput = {
        fullName: data.n,
        email: data.e,
        phone: data.p,
        linkedinGithub: data.l
    };

    return (
        <div className="min-h-screen bg-slate-100 flex flex-col">
            {/* Header */}
            <header className="bg-white border-b border-slate-200 sticky top-0 z-50">
                <div className="container mx-auto px-4 py-3 flex justify-between items-center">
                    <div className="flex items-center space-x-2">
                         <LogoIcon className="h-6 w-6 text-blue-600" />
                         <span className="font-bold text-slate-900 tracking-tight text-lg">JobHero<span className="text-blue-600">.ai</span></span>
                    </div>
                    <a href="/" className="text-xs sm:text-sm font-bold text-white bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded-full transition-colors shadow-sm hover:shadow-md">
                        ✨ Create Your Own
                    </a>
                </div>
            </header>

            {/* Resume Content */}
            <main className="flex-grow container mx-auto p-4 sm:p-8 flex justify-center">
                <div className="w-full max-w-[850px] bg-white rounded-xl shadow-2xl overflow-hidden animate-in fade-in slide-in-from-bottom-4 duration-700">
                    <ResumePreview 
                        text={data.r} 
                        template={data.t as TemplateType} 
                        userInput={mockUserInput} 
                    />
                </div>
            </main>

            {/* Footer */}
            <footer className="bg-white border-t border-slate-200 py-6 text-center">
                <p className="text-slate-500 text-sm mb-2">Generated by JobHero AI powered by Gemini 3.0</p>
                <a href="/" className="text-blue-600 font-semibold hover:underline text-sm">Build your own resume for free →</a>
            </footer>
        </div>
    );
};